name: "Report a vulnerability in our projects"
description: Describe a vulnerability in our projects and suggest how to make it better.
title: "[vulnerability] [project] [severe/moderate/mild] \"Quoted vulnerability in the project\""
labels: ["vulnerability"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to check a vulnerability of the projects listed here!  
        Please make sure to give it a correct title. e.g. _[vulnerability] [server] [severe] Outdated version of quart_
  - type: dropdown
    id: projects
    attributes:
      label: Affected product(s)
      description: What are the products that were affected by?
      options:
        - "Server"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe why the project has a vulnerability or two.
      placeholder: e.g. The package has a outdated version
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Provide a solution for the issue.
      placeholder: e.g. Update package to the latest version
    validations:
      required: true
